graph TD
    IMG[Node With Image] --> Plain[Plain Node]

%% OXDRAW IMAGE IMG image/png iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAnElEQVR42sXOyQ2AMBBD0VRCOxRCQ3QcBOIQRdlmxnYs/av1Uv533L7ydYZKudgWwHcSQEAAEQQM4EVAAR4EHGBFUAAWBA2wiqACVhB0wAwhAYwQMkAPIQW0EHJAjdgCQCLcABQiBEAg4oD3KIDAAAIIHMCJwAIcCDzAiOAADAgeYBHBBSwg+IAJQgMYIHSADkILaCD0gAqxB1AgHskMJMLzpszkAAAAAElFTkSuQmCC
