graph TD
    sub[[Subroutine]] --> cyl[(Database)]
    cyl --> hex{{Prepare}}
    hex --> stop(((Stop)))
    stop --> lean[/Lean/]
    lean --> leanAlt[\Lean\]
    leanAlt --> trap[/Priority\]
    trap --> trapAlt[\Manual/]
    trapAlt --> asym>Skewed]
    asym --> stadium([Terminal])
