graph TD
A[Thing] -->|Get money| B(Go shopping)
B --> C{Let me think}
C -.->|One| D[Laptop]
C -.->|Two| E[iPhone]
C -.->|Three| F[Car]

%% OXDRAW LAYOUT START
%% {
%%   "nodes": {
%%     "B": {
%%       "x": 762.67706,
%%       "y": 281.45346
%%     },
%%     "E": {
%%       "x": 763.09564,
%%       "y": 354.74152
%%     },
%%     "A": {
%%       "x": 526.4829,
%%       "y": 278.37076
%%     },
%%     "C": {
%%       "x": 565.3781,
%%       "y": 349.71103
%%     },
%%     "F": {
%%       "x": 761.2967,
%%       "y": 438.2988
%%     },
%%     "D": {
%%       "x": 521.7253,
%%       "y": 475.87067
%%     }
%%   },
%%   "edges": {},
%%   "node_styles": {},
%%   "edge_styles": {
%%     "A --> B": {
%%       "line": "dashed",
%%       "color": "#1153c5",
%%       "arrow": "both"
%%     }
%%   }
%% }
%% OXDRAW LAYOUT END
