graph TD
A[Thing] -->|Get money| B(Go shopping)
B --> C{Let me think}
C -.->|One| D[Laptop]
C -.->|Two| E[iPhone]
C -.->|Three| F[Car]

%% OXDRAW LAYOUT START
%% {
%%   "nodes": {
%%     "C": {
%%       "x": 398.25525,
%%       "y": 331.02637
%%     },
%%     "A": {
%%       "x": 497.7188,
%%       "y": 210.78442
%%     }
%%   },
%%   "edges": {}
%% }
%% OXDRAW LAYOUT END
