graph TD
A[Thing] -->|Get money| B(Go shopping)
B --> C{Let me think}
C -.->|One| D[Laptop]
C -.->|Two| E[iPhone]
C -.->|Three| F[Car]

%% OXDRAW LAYOUT START
%% {
%%   "nodes": {
%%     "C": {
%%       "x": 398.25525,
%%       "y": 330.93646
%%     },
%%     "E": {
%%       "x": 526.2337,
%%       "y": 471.22128
%%     },
%%     "A": {
%%       "x": 471.78036,
%%       "y": 216.8561
%%     },
%%     "F": {
%%       "x": 367.07233,
%%       "y": 443.39658
%%     },
%%     "D": {
%%       "x": 206.29227,
%%       "y": 383.86423
%%     }
%%   },
%%   "edges": {},
%%   "node_styles": {},
%%   "edge_styles": {
%%     "A --> B": {
%%       "line": "dashed",
%%       "color": "#1153c5",
%%       "arrow": "both"
%%     }
%%   }
%% }
%% OXDRAW LAYOUT END
